version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.20.2-browsers
    working_directory: ~/project

jobs:
  test:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run Nightwatch tests
          command: npx nightwatch --headless

workflows:
  version: 2
  test:
    jobs:
      - test
