version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:20.12.2

    steps:
      - checkout

      - run:
          name: Install Google Chrome
          command: |
            sudo apt update
            sudo apt install -y google-chrome-stable

      - run:
          name: Install Node.js dependencies
          working_directory: ~/project/my-nightwatch-project
          command: npm ci

      - run:
          name: Fix bin permissions
          working_directory: ~/project/my-nightwatch-project
          command: chmod -R +x ./node_modules/.bin

      - run:
          name: Run Jest tests
          working_directory: ~/project/my-nightwatch-project
          command: npx jest api-tests/auth.test.js

      - run:
          name: Run Nightwatch tests
          working_directory: ~/project/my-nightwatch-project
          command: npx nightwatch tests/

workflows:
  build-and-test-workflow:
    jobs:
      - build-and-test
