version: 2.1
jobs:
  build-and-test:
    docker:
      - image: cimg/node:20.12.2 # Use a Node.js image suitable for your project

    steps:
      - checkout # This step checks out your code from GitHub

      - run:
          name: "Install Node.js Dependencies"
          command: |
            # IMPORTANT: Navigate into your project folder where package.json is located
            cd my-nightwatch-project
            npm install

      - run:
          name: "Run Nightwatch/Jest Tests"
          command: |
            # IMPORTANT: Ensure you are in the project folder to run tests
            cd my-nightwatch-project
            npx jest api-tests/auth.test.js

workflows: # Defines how your jobs are orchestrated
  build-and-test-workflow: # This is the name of your workflow
    jobs:
      - build-and-test # This tells the workflow to run the 'build-and-test' job
