version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.2.0 # You can change to your preferred Node version
    working_directory: ~/project

jobs:
  ui-tests:
    executor: node-executor
    steps:
      - checkout
      - run: npm install
      - run: npx nightwatch
      - store_artifacts:
          path: tests_output
          destination: ui-test-results

  api-tests:
    executor: node-executor
    steps:
      - checkout
      - run: npm install
      - run: npx jest api-tests
      - store_artifacts:
          path: coverage
          destination: api-test-results

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - ui-tests
      - api-tests
