version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.2.0
    working_directory: ~/project

jobs:
  install-deps:
    executor: node-executor
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo apt install -y google-chrome-stable
      - run: npm install

  ui-tests:
    executor: node-executor
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo apt install -y google-chrome-stable
      - run: npm install
      - run: npx nightwatch --headless
      - store_artifacts:
          path: tests_output
          destination: ui-test-results

  api-tests:
    executor: node-executor
    steps:
      - checkout
      - run: npm install
      - run: npx jest api-tests
      - store_artifacts:
          path: coverage
          destination: api-test-results

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - install-deps
      - ui-tests:
          requires:
            - install-deps
      - api-tests:
          requires:
            - install-deps
