version: 2.1
jobs:
  build-and-test:
    docker:
      - image: cimg/node:20.12.2 # Use a Node.js image suitable for your project

    steps:
      - checkout # This step checks out your code from GitHub

      - run:
          name: "Install Node.js Dependencies"
          command: |
            cd my-nightwatch-project
            npm install

      - run:
          name: "Run Nightwatch/Jest Tests"
          command: |
            cd my-nightwatch-project
            # CHANGE THIS LINE: Use npm exec instead of npx for better compatibility
            npm exec jest -- api-tests/auth.test.js # Executes your Jest tests

workflows:
  build-and-test-workflow:
    jobs:
      - build-and-test
      
