version: 2.1 # Specifies the CircleCI config version
jobs:        # Defines the individual build steps
  build-and-test: # This is the name of your job
    docker:
      - image: cimg/node:20.12.2 # The environment where your job runs

    steps:
      - checkout
      - run:
          name: "Install Node.js Dependencies"
          command: |
            cd my-nightwatch-project
            npm install
      - run:
          name: "Run Nightwatch/Jest Tests"
          command: |
            cd my-nightwatch-project
            npx jest api-tests/auth.test.js

workflows: # Defines how your jobs are orchestrated
  build-and-test-workflow: # This is the name of your workflow
    jobs:
      - build-and-test # This tells the workflow to run the 'build-and-test' job
