version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:20.12.2

    steps:
      - checkout # gets your repo code

      - run:
          name: Install Node.js dependencies
          command: |
            npm ci

      - run:
          name: Fix bin permissions
          command: chmod -R +x ./node_modules/.bin

      - run:
          name: Run Nightwatch/Jest tests
          command: npx jest api-tests/auth.test.js
      - run:
          name: Run Nightwatch tests
          command: npx nightwatch tests/nightwatch-tests/

workflows:
  build-and-test-workflow:
    jobs:
      - build-and-test
